-- ============================================
-- SUPABASE DATABASE SCHEMA
-- Energy Report System - Báo Cáo Năng Lượng
-- ============================================

-- 🔧 HƯỚNG DẪN SỬ DỤNG:
-- 1. Truy cập https://supabase.com/dashboard
-- 2. Chọn project của bạn
-- 3. Vào menu SQL Editor
-- 4. Copy toàn bộ nội dung file này và paste vào
-- 5. Click "Run" để tạo bảng

-- ============================================
-- 1. WATER READINGS - Bảng nước
-- ============================================
create table if not exists water_readings (
    id bigint generated by default as identity primary key,
    date date not null,
    shift text not null check (shift in ('sang', 'toi')),
    location_code text not null,
    location_name_vi text,
    location_name_cn text,
    value decimal(10, 3),
    unit text default 'm3',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Index cho tìm kiếm nhanh
create index if not exists water_readings_date_idx on water_readings(date);
create index if not exists water_readings_date_shift_idx on water_readings(date, shift);
create index if not exists water_readings_location_idx on water_readings(location_code);

-- RLS Policy
alter table water_readings enable row level security;
create policy "Enable read for authenticated users" on water_readings for select to authenticated using (true);
create policy "Enable insert for authenticated users" on water_readings for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on water_readings for update to authenticated using (true);

-- ============================================
-- 2. ELECTRIC READINGS - Bảng điện
-- ============================================
create table if not exists electric_readings (
    id bigint generated by default as identity primary key,
    date date not null,
    shift text not null check (shift in ('sang', 'toi')),
    location_code text not null,
    location_name_vi text,
    location_name_cn text,
    value decimal(10, 3),
    unit text default 'kwh',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Index cho tìm kiếm nhanh
create index if not exists electric_readings_date_idx on electric_readings(date);
create index if not exists electric_readings_date_shift_idx on electric_readings(date, shift);
create index if not exists electric_readings_location_idx on electric_readings(location_code);

-- RLS Policy
alter table electric_readings enable row level security;
create policy "Enable read for authenticated users" on electric_readings for select to authenticated using (true);
create policy "Enable insert for authenticated users" on electric_readings for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on electric_readings for update to authenticated using (true);

-- ============================================
-- 3. GAS READINGS - Bảng khí gas
-- ============================================
create table if not exists gas_readings (
    id bigint generated by default as identity primary key,
    date date not null,
    shift text not null check (shift in ('sang', 'toi')),
    product_line text not null,
    product_name_vi text,
    product_name_cn text,
    value decimal(10, 3),
    unit text default 'm3',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Index cho tìm kiếm nhanh
create index if not exists gas_readings_date_idx on gas_readings(date);
create index if not exists gas_readings_date_shift_idx on gas_readings(date, shift);
create index if not exists gas_readings_product_idx on gas_readings(product_line);

-- RLS Policy
alter table gas_readings enable row level security;
create policy "Enable read for authenticated users" on gas_readings for select to authenticated using (true);
create policy "Enable insert for authenticated users" on gas_readings for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on gas_readings for update to authenticated using (true);

-- ============================================
-- 4. STEAM READINGS - Bảng hơi nóng
-- ============================================
create table if not exists steam_readings (
    id bigint generated by default as identity primary key,
    date date not null,
    shift text not null check (shift in ('sang', 'toi')),
    process_step text not null,
    process_name_vi text,
    process_name_cn text,
    value decimal(10, 3),
    unit text default 'kg',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Index cho tìm kiếm nhanh
create index if not exists steam_readings_date_idx on steam_readings(date);
create index if not exists steam_readings_date_shift_idx on steam_readings(date, shift);
create index if not exists steam_readings_process_idx on steam_readings(process_step);

-- RLS Policy
alter table steam_readings enable row level security;
create policy "Enable read for authenticated users" on steam_readings for select to authenticated using (true);
create policy "Enable insert for authenticated users" on steam_readings for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on steam_readings for update to authenticated using (true);

-- ============================================
-- 5. LOCATIONS - Bảng vị trí đo
-- ============================================
create table if not exists locations (
    id bigint generated by default as identity primary key,
    code text unique not null,
    name_vi text not null,
    name_cn text,
    energy_type text not null check (energy_type in ('water', 'electric', 'gas', 'steam')),
    area text,
    description text,
    is_active boolean default true,
    created_at timestamp with time zone default now()
);

-- Insert default water locations
insert into locations (code, name_vi, name_cn, energy_type, area) values
('B12-W', 'Phòng giặt B12', '洗衣房', 'water', 'B12'),
('B4.1-W', 'Khu dầu cọ B4.1', '棕榈油热水', 'water', 'B4.1'),
('B4.2-W', 'Phòng điện giải B4.2', '电解室', 'water', 'B4.2'),
('B11.1-W', 'Nấu tương B11.1', '煮酱', 'water', 'B11.1'),
('B17-W', 'Nhà vệ sinh CĐ3 B17', '三工程厕所', 'water', 'B17'),
('CD3-W-OUT', 'Bồn Nước nóng CĐ3 (Ngoài)', '热水缸(外)', 'water', 'CĐ3'),
('B11.2-W', 'Rửa dụng cụ CD3 B11.2', '清洗区(内)', 'water', 'B11.2')
on conflict (code) do nothing;

-- Insert default electric locations
insert into locations (code, name_vi, name_cn, energy_type, area) values
('MP2.2-01', 'Trạm khí gas', '天然气站', 'electric', 'MP2.2'),
('MP2.2-02', 'Khu vực chiên CĐ2', '油炸区', 'electric', 'MP2.2'),
('MP2.3-01', 'Khu vực sấy nack CĐ2', '干烧区', 'electric', 'MP2.3'),
('MP2.3-02', 'Khu vực nướng CĐ2', '烘烤区', 'electric', 'MP2.3'),
('MP2.3-03', 'Khu sấy phôi nack', '胚料烘干', 'electric', 'MP2.3'),
('MP2.3-05', 'Máy sắp phôi CĐ2', '排列机', 'electric', 'MP2.3'),
('MP2.3-06', 'Máy sấy rong biển CĐ2', '海苔烘干', 'electric', 'MP2.3'),
('MP2.3-07', 'Khu đóng gói rong biển CĐ3', '包装区', 'electric', 'MP2.3'),
('MP2.3-08', 'Sấy phôi CĐ2', '胚料干燥', 'electric', 'MP2.3'),
('MP2.4-01', 'Tủ điện ổ cắm sửa chữa', '插座柜', 'electric', 'MP2.4'),
('MP2.4-02', 'Sấy bánh tuyết CĐ2', '雪饼烘干', 'electric', 'MP2.4'),
('MP2.4-03', 'Sấy bánh mỏng CĐ2', '薄饼烘干', 'electric', 'MP2.4'),
('MP2.4-04', 'Phòng nấu tương CĐ2', '煮酱区', 'electric', 'MP2.4'),
('MP2.4-05', 'Máy lạnh CĐ3', '空调', 'electric', 'MP2.4'),
('MP2.4-06', 'Đóng gói nack CĐ3', '包装', 'electric', 'MP2.4'),
('MP2.4-08', 'Sấy bánh phô mai, bánh đậu CĐ2', '芝士饼烘干', 'electric', 'MP2.4'),
('MP2.5-02', 'Đóng gói sen bei CĐ3', '仙贝包装', 'electric', 'MP2.5'),
('MP2.5-05', 'Máy hút chân không CĐ2', '真空机', 'electric', 'MP2.5'),
('MP2.5-06', 'Đóng gói bánh tuyết CĐ3', '雪饼包装', 'electric', 'MP2.5'),
('MP2.5-07', 'Đóng gói BBMM CĐ3', '米果包装', 'electric', 'MP2.5'),
('MP2.6-01', 'Khu đóng gói phía ngoài CĐ3', '外包装', 'electric', 'MP2.6'),
('MP2.6-02', 'Máy lạnh VP bánh gạo + phòng thay đồ CĐ3', '空调(办)', 'electric', 'MP2.6'),
('MP2.6-03', 'AHU máy lạnh CĐ2', '空调机组', 'electric', 'MP2.6'),
('MP2.6-04', 'Máy lạnh lưu phôi CĐ1', '胚料冷藏', 'electric', 'MP2.6'),
('MP2.6-05', 'Kho lạnh + phòng đường CĐ2', '冷库', 'electric', 'MP2.6'),
('MP2.6-07', 'Quạt hút đóng gói CĐ3', '排气扇', 'electric', 'MP2.6'),
('MP2.7-01', 'Khu tạo bột CĐ1', '制粉区', 'electric', 'MP2.7'),
('MP2.7-02', 'Khu rửa gạo CĐ1', '洗米区', 'electric', 'MP2.7'),
('MP2.7-03', 'Khu vực nghiền CĐ1', '粉碎区', 'electric', 'MP2.7'),
('MP2.7-05', 'Khu hấp CĐ1', '蒸练区', 'electric', 'MP2.7'),
('MP2.7-06', 'Sấy phôi CĐ1', '胚料干燥', 'electric', 'MP2.7'),
('MP2.11-01', 'Máy tạo bột khu 2 CĐ1', '制粉机二区', 'electric', 'MP2.11'),
('MP2.11-02', 'Khu hấp thành hình CĐ1', '蒸练成型', 'electric', 'MP2.11'),
('MP2.11-03', 'Bánh cuộn (Đóng gói)', '蛋糕卷', 'electric', 'MP2.11')
on conflict (code) do nothing;

-- Insert default gas product lines
insert into locations (code, name_vi, name_cn, energy_type, area) values
('GAS-HH', 'Công đoạn 2 - Rong biển', '厚烧', 'gas', 'CĐ2'),
('GAS-XB', 'Công đoạn 2 - Bánh tuyết', '雪饼', 'gas', 'CĐ2'),
('GAS-SB', 'Công đoạn 2 - Sen bei', '仙贝', 'gas', 'CĐ2'),
('GAS-BBMM', 'Công đoạn 2 - BBMM', '米果', 'gas', 'CĐ2')
on conflict (code) do nothing;

-- Insert default steam process steps
insert into locations (code, name_vi, name_cn, energy_type, area) values
('STM-01', 'Công đoạn 1 (5#)', '一工程', 'steam', 'CĐ1'),
('STM-02', 'Công đoạn 2 - Bánh tuyết (1#)', '雪饼', 'steam', 'CĐ2'),
('STM-03', 'Công đoạn 2 - Rong biển (2#)', '厚烧', 'steam', 'CĐ2'),
('STM-04', 'Công đoạn 2 - SNACK (3#)', '小小酥', 'steam', 'CĐ2'),
('STM-05', 'Công đoạn 3 - Máy khử ẩm (4#)', '除湿机', 'steam', 'CĐ3')
on conflict (code) do nothing;

-- RLS Policy for locations
alter table locations enable row level security;
create policy "Enable read for all users" on locations for select to authenticated using (true);
create policy "Enable insert for authenticated users" on locations for insert to authenticated with check (true);
create policy "Enable update for authenticated users" on locations for update to authenticated using (true);

-- ============================================
-- 6. USERS/PROFILES - Bảng người dùng (mở rộng)
-- ============================================
create table if not exists user_profiles (
    id uuid references auth.users on delete cascade primary key,
    email text,
    full_name text,
    role text default 'user' check (role in ('admin', 'user', 'viewer')),
    department text,
    phone text,
    is_active boolean default true,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- RLS Policy
alter table user_profiles enable row level security;
create policy "Users can view own profile" on user_profiles for select to authenticated using (auth.uid() = id);
create policy "Users can update own profile" on user_profiles for update to authenticated using (auth.uid() = id);
create policy "Admins can manage all profiles" on user_profiles for all to authenticated using (
    exists (
        select 1 from user_profiles
        where id = auth.uid() and role = 'admin'
    )
);

-- Auto create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.user_profiles (id, email, full_name)
    values (new.id, new.email, new.raw_user_meta_data->>'full_name');
    return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

-- ============================================
-- 7. AUDIT LOG - Bảng lịch sử chỉnh sửa
-- ============================================
create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users,
    action text not null,
    table_name text not null,
    record_id bigint,
    old_data jsonb,
    new_data jsonb,
    ip_address text,
    created_at timestamp with time zone default now()
);

-- Index for audit log
create index if not exists audit_log_user_idx on audit_log(user_id);
create index if not exists audit_log_table_idx on audit_log(table_name);
create index if not exists audit_log_created_idx on audit_log(created_at);

-- ============================================
-- 8. VIEWS - Tạo view cho dashboard
-- ============================================

-- View tổng hợp nước theo ngày
create or replace view water_daily_summary as
select 
    date,
    shift,
    count(*) as location_count,
    sum(value) as total_value,
    avg(value) as avg_value,
    max(value) as max_value,
    min(value) as min_value
from water_readings
group by date, shift
order by date desc, shift;

-- View tổng hợp điện theo ngày
create or replace view electric_daily_summary as
select 
    date,
    shift,
    count(*) as location_count,
    sum(value) as total_value,
    avg(value) as avg_value,
    max(value) as max_value,
    min(value) as min_value
from electric_readings
group by date, shift
order by date desc, shift;

-- View tổng hợp gas theo ngày
create or replace view gas_daily_summary as
select 
    date,
    shift,
    count(*) as product_count,
    sum(value) as total_value,
    avg(value) as avg_value
from gas_readings
group by date, shift
order by date desc, shift;

-- View tổng hợp hơi nóng theo ngày
create or replace view steam_daily_summary as
select 
    date,
    shift,
    count(*) as process_count,
    sum(value) as total_value,
    avg(value) as avg_value
from steam_readings
group by date, shift
order by date desc, shift;

-- ============================================
-- CÁC HÀM TiỆN ÍCH
-- ============================================

-- Hàm lấy tổng năng lượng theo tháng
create or replace function get_monthly_totals(p_start_date date, p_end_date date)
returns table (
    energy_type text,
    total_value numeric
) as $$
begin
    return query
    select 'water'::text, coalesce(sum(value), 0) from water_readings where date between p_start_date and p_end_date
    union all
    select 'electric'::text, coalesce(sum(value), 0) from electric_readings where date between p_start_date and p_end_date
    union all
    select 'gas'::text, coalesce(sum(value), 0) from gas_readings where date between p_start_date and p_end_date
    union all
    select 'steam'::text, coalesce(sum(value), 0) from steam_readings where date between p_start_date and p_end_date;
end;
$$ language plpgsql security definer;

-- ============================================
-- HOÀN TẤT
-- ============================================
select '✅ Database schema đã được tạo thành công!' as status;